# Generated by Django 6.0.6 on 2026-06-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=2)),
                ('retail_price', models.DecimalField(decimal_places=6, max_digits=8)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('geocode_quality', models.CharField(max_length=16)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='routing_fue_state_a0c837_idx'), models.Index(fields=['geocode_quality'], name='routing_fue_geocode_426a4b_idx')],
            },
        ),
    ]
